[package]
name = "noita-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive"] }
fs_extra = "1.3.0"

[dependencies.windows]
version = "0.44.0"
features = ["Storage"]
